version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant@sha256:955afecd2b2df764f3a7b8e1628d99a88d1a738c5c2473e844d64e9355faae52
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  python:
    image: python@sha256:9c1d9ed7593f2552a4ea47362ec0d2ddf5923458a53d0c8e30edf8b398c94a31
    command: ["sh", "-c", "pip install -r requirements.txt && python app.py"]
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-python
    environment:
      - PIP_REQUIRE_VIRTUALENV=0
    entrypoint: []
    depends_on:
      - qdrant
