FROM python:3.12-slim@sha256:610020b9ad8ee92798f1dbe18d5e928d47358db698969d12730f9686ce3a3191

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

# Optional: Install Python sqlite package (usually built-in)
RUN python -m ensurepip && pip install --upgrade pip

WORKDIR /app
