version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant@sha256:955afecd2b2df764f3a7b8e1628d99a88d1a738c5c2473e844d64e9355faae52
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  jupyter:
    image: quay.io/jupyter/datascience-notebook@sha256:4b93f99fc05b7a4d2318bc1a25ca36083132bb9dfdf280c2e7edd7f6a3075a11
    ports:
      - "8888:8888"
    volumes:
      - ./app:/home/jovyan/work
    command: ["sh", "-c", "pip install -r /home/jovyan/work/requirements.txt && start-notebook.py --NotebookApp.token='' --NotebookApp.password=''"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
