#!/bin/bash

# XML Validation Script
# Validates XML files generated by export-logs.sh against the repository-commits.xsd schema

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

SCHEMA_FILE="repository-commits.xsd"
XML_DIR="XML_commit_messages"

echo -e "${GREEN}XML Validation Script${NC}"
echo "============================="

# Check if xmllint is available
if ! command -v xmllint &> /dev/null; then
    echo -e "${RED}Error: xmllint is not installed${NC}"
    echo -e "${YELLOW}Install it with: sudo apt-get install libxml2-utils (Ubuntu/Debian)${NC}"
    echo -e "${YELLOW}Or: brew install libxml2 (macOS)${NC}"
    exit 1
fi

# Check if schema file exists
if [ ! -f "$SCHEMA_FILE" ]; then
    echo -e "${RED}Error: Schema file '$SCHEMA_FILE' not found${NC}"
    exit 1
fi

# Check if XML directory exists
if [ ! -d "$XML_DIR" ]; then
    echo -e "${RED}Error: XML directory '$XML_DIR' not found${NC}"
    echo -e "${YELLOW}Run export-logs.sh first to generate XML files${NC}"
    exit 1
fi

echo -e "${YELLOW}Schema file:${NC} $SCHEMA_FILE"
echo -e "${YELLOW}XML directory:${NC} $XML_DIR"
echo ""

# Validate schema file itself
echo -e "${YELLOW}Validating schema file...${NC}"
if xmllint --noout "$SCHEMA_FILE" 2>/dev/null; then
    echo -e "${GREEN}✓ Schema file is valid${NC}"
else
    echo -e "${RED}✗ Schema file is invalid${NC}"
    exit 1
fi

echo ""

# Find and validate all XML files
XML_FILES_FOUND=0
VALID_FILES=0
INVALID_FILES=0

echo -e "${YELLOW}Validating XML files...${NC}"
echo ""

for xml_file in "$XML_DIR"/*.xml; do
    if [ -f "$xml_file" ]; then
        XML_FILES_FOUND=$((XML_FILES_FOUND + 1))
        filename=$(basename "$xml_file")
        
        echo -n "Validating $filename... "
        
        if xmllint --noout --schema "$SCHEMA_FILE" "$xml_file" 2>/dev/null; then
            echo -e "${GREEN}✓ VALID${NC}"
            VALID_FILES=$((VALID_FILES + 1))
        else
            echo -e "${RED}✗ INVALID${NC}"
            INVALID_FILES=$((INVALID_FILES + 1))
            
            # Show detailed validation errors
            echo -e "${RED}Validation errors:${NC}"
            xmllint --noout --schema "$SCHEMA_FILE" "$xml_file" 2>&1 | sed 's/^/  /'
            echo ""
        fi
    fi
done

echo ""
echo -e "${YELLOW}Validation Summary:${NC}"
echo -e "${YELLOW}  Files found:${NC} $XML_FILES_FOUND"
echo -e "${GREEN}  Valid files:${NC} $VALID_FILES"
echo -e "${RED}  Invalid files:${NC} $INVALID_FILES"

if [ $XML_FILES_FOUND -eq 0 ]; then
    echo -e "${YELLOW}No XML files found in $XML_DIR${NC}"
    exit 1
elif [ $INVALID_FILES -gt 0 ]; then
    echo ""
    echo -e "${RED}Some files failed validation${NC}"
    exit 1
else
    echo ""
    echo -e "${GREEN}✓ All XML files are valid according to the schema${NC}"
fi
